services:
  rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    hostname: rabbitmq
    restart: always
    env_file: "vars_rabbitmq.env"      
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  postgres:
    image: postgres:17.2
    restart: always
    hostname: postgres
    env_file: "vars_postgres.env"
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  bot_handler:
    build:
      context: /BotHandler/
      dockerfile: Dockerfile
    image: bothandler
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    env_file: "vars_spring.env"
  service:
    build:
      context: /Service/
      dockerfile: Dockerfile
    image: service
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - bot_handler
    env_file: "vars_spring.env"
